[[Unsio]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "460d55a49623649810d6d243c11fdce1ccfd7374"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Unsio.download]]
    sha256 = "5823cf37b2ee774c01494c2b8949215c8f5245f94d357467243e33daeb4387d6"
    url = "https://github.com/vleugelcomplement/Unsio_jll/releases/download/Unsio-v1.0.1+0/Unsio.v1.0.1.x86_64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[Unsio]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57f80f2ab643ed1dd5c59c572b70757310e0c661"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Unsio.download]]
    sha256 = "a60b45f7abcee532eec100cf4542bb22d7c2ec7717b7485ce7a11937aad6a43b"
    url = "https://github.com/vleugelcomplement/Unsio_jll/releases/download/Unsio-v1.0.1+0/Unsio.v1.0.1.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[Unsio]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c28993a273460f692bcdcfb4e8352f3d8ac0c167"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Unsio.download]]
    sha256 = "7bcd599214fcbb3832d931e77200cb467915d458b5d647cf5fb36411787448ff"
    url = "https://github.com/vleugelcomplement/Unsio_jll/releases/download/Unsio-v1.0.1+0/Unsio.v1.0.1.x86_64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[Unsio]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c76e0af5a0b51dc2d9aa8e7979b5e50a7df6ab1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Unsio.download]]
    sha256 = "daf7d3fa0674b69547c61ee4793bba53ae785ba0bf4140186fce2f4b1f71e1ac"
    url = "https://github.com/vleugelcomplement/Unsio_jll/releases/download/Unsio-v1.0.1+0/Unsio.v1.0.1.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"

[[unsio]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90d2fcbd09be97dba81ba5547cff7b0e2a7a9b23"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[unsio.download]]
    sha256 = "1f30bd46a2f4958b05e91ae75c7eb30208f1bdab4e998e31d46c35627d2ce8c8"
    url = "https://github.com/vleugelcomplement/Unsio_jll/releases/download/Unsio-v1.0.1+0/Unsio.v1.0.1.x86_64-linux-gnu-libgfortran4-cxx03.tar.gz"
[[unsio]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6146825f1432d036c21e5a7dd1eb396e49a65284"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[unsio.download]]
    sha256 = "0117db418ecc9303d3db87f60597729e29b1f231e5284e5b4a2add03d4f2296b"
    url = "https://github.com/vleugelcomplement/Unsio_jll/releases/download/Unsio-v1.0.1+0/Unsio.v1.0.1.x86_64-linux-gnu-libgfortran4-cxx11.tar.gz"
[[unsio]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5985619a27d981082f8d913c44e40672555787b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[unsio.download]]
    sha256 = "7a07ac51dab9e8bd97ca149db7b3550fd5bb58ab9248099355069df6d1e3c21b"
    url = "https://github.com/vleugelcomplement/Unsio_jll/releases/download/Unsio-v1.0.1+0/Unsio.v1.0.1.x86_64-linux-gnu-libgfortran5-cxx03.tar.gz"
[[unsio]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0005c46c08e44e05d10027442c989fd96b93484b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[unsio.download]]
    sha256 = "4d6acf34d4a5066d0b8d71efd207d2d45eccf6ae1e93f46bd647c5f8633f2fbf"
    url = "https://github.com/vleugelcomplement/Unsio_jll/releases/download/Unsio-v1.0.1+0/Unsio.v1.0.1.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
