# Autogenerated wrapper script for Unsio_jll for x86_64-linux-gnu-libgfortran5-cxx03
export libunsio

using SQLite_jll
using HDF5_jll
JLLWrappers.@generate_wrapper_header("Unsio")
JLLWrappers.@declare_library_product(libunsio, "libunsio.so")
function __init__()
    JLLWrappers.@generate_init_header(SQLite_jll, HDF5_jll)
    JLLWrappers.@init_library_product(
        libunsio,
        "lib64/libunsio.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
